name: Update RSS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions: write-all

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.compare.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm i
      - name: Fetch RSS data
        run: |
          curl -LO https://sharo-jef.github.io/arknights-ost-rss/rss.xml
          npx fast-xml-parser rss.xml -o rss.json
          jq -r '.rss.channel.item[].title' | sort | tee rss.txt
      - name: Fetch API data
        run: curl -LO https://monster-siren.hypergryph.com/api/songs | jq -r '.data.list[].name' | sort | tee api.txt
      - name: Compare
        id: compare
        run: |
          set +e
          diff rss.txt api.txt
          echo "result=$?" >> "$GITHUB_OUTPUT"
  deploy:
    needs: update
    if: ${{ needs.update.outputs.result == 1 }}
    uses: ./.github/workflows/jekyll-gh-pages.yml
  update_last_update_data:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update last_update.md
        run: |
          echo "---
          layout: default
          title: Last update
          nav_order: 2
          ---

          # Last update

          \`$(date)\`
          " > last_update.md
      - name: Show
        run: cat last_update.md
      - name: Push
        run: |
          git config user.name 'GitHub Actions [bot]'
          git add last_update.md
          git commit -m 'Update last_update.md'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
